version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: students
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql

volumes:
  data: